boardapp/urls.py
from django.urls import path

from boardapp.views import BoardListView, BoardCreateView, BoardDetailView, BoardUpdateView, BoardDeleteView

app_name = 'boardapp'

urlpatterns = [
    path('list/', BoardListView.as_view(), name='list'),
    path('create/', BoardCreateView.as_view(), name='create'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),
]

chatapp/urls.py
from django.urls import path

from chatapp.views import main_view

app_name = 'chatapp'

urlpatterns = [
    path('', main_view, name='main_view'),
]

health_partner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from health_partner.views import HomeView

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),

                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('boards/', include('boardapp.urls')),
                  path('trainers/', include('trainerapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('videos/', include('videoapp.urls')),
                  path('trainercomments/', include('trainercommentapp.urls')),
                  path('chats/', include('chatapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boardapp/models.py
from django.conf import settings
from django.db import models


# Create your models here.
from accountapp.models import User


class Board(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')

    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    image = models.ImageField(upload_to='board/', null=True, blank=True)
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일")

    def __str__(self):
        return self.title

    @property
    def update_counter(self):
        self.hits = self.hits + 1
        self.save()

    class Meta:
        db_table = 'Q&A게시판'
        verbose_name = 'Q&A게시판'
        verbose_name_plural = 'Q&A게시판'

boardapp/forms.py
from django import forms
from django.forms import ModelForm

from boardapp.models import Board


class BoardCreationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BoardCreationForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = '제목'
        self.fields['title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'autofocus': True,
        })

    class Meta:
        model = Board
        fields = ['title', 'content', 'image']

boardapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.checks import messages
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import FormMixin, UpdateView, DeleteView

from boardapp.decorators import board_ownership_required
from boardapp.forms import BoardCreationForm
from boardapp.models import Board
from commentapp.forms import CommentCreationForm

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class BoardCreateView(CreateView):
    model = Board
    form_class = BoardCreationForm
    template_name = 'boardapp/board_create.html'

    def form_valid(self, form):
        temp_board = form.save(commit=False)
        temp_board.writer = self.request.user
        temp_board.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('boardapp:detail', kwargs={'pk': self.object.pk})

class BoardDetailView(DetailView, FormMixin):
    model = Board
    form_class = CommentCreationForm
    context_object_name = 'target_board'
    template_name = 'boardapp/board_detail.html'


@method_decorator(board_ownership_required, 'get')
@method_decorator(board_ownership_required, 'post')
class BoardUpdateView(UpdateView):
    model = Board
    form_class = BoardCreationForm
    context_object_name = 'target_board'
    template_name = 'boardapp/board_update.html'

    def get_success_url(self):
        return reverse('boardapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(board_ownership_required, 'get')
@method_decorator(board_ownership_required, 'post')
class BoardDeleteView(DeleteView):
    model = Board
    context_object_name = 'target_board'
    success_url = reverse_lazy('boardapp:list')
    template_name = 'boardapp/board_delete.html'



class BoardListView(ListView):
    model = Board
    context_object_name = 'board_list'
    template_name = 'boardapp/board_list.html'
    paginate_by = 8



    def get_queryset(self):

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        board_list = Board.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_board_list = board_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__user_id__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_board_list = board_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_board_list = board_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_board_list = board_list.filter(content__icontains=search_keyword)

                return search_board_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return board_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type

        return context





boardapp/templates/boardapp/board_create.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

    <script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">


    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4> 글쓰기 </h4>
        </div>
        <form action="{% url 'boardapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3">
        </form>
    </div>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}


{#{% block mobileView %}#}
{#    <meta name="viewport" content="width=800, user-scalable=yes">#}
{#{% endblock %}#}
{##}
{#{% block summernote %}#}
{#    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.css" rel="stylesheet">#}
{#    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.js"></script>#}
{#    <script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>#}
{#    <script>#}
{#        $(document).ready(function () {#}
{#            $('#id_content').summernote({#}
{#                placeholder: '내용을 입력해주세요.',#}
{#                height: 500,#}
{#                minHeight: 500,#}
{#                maxHeight: 500,#}
{#                lang: 'ko-KR',#}
{##}
{#                toolbar: [#}
{#                    ['style', ['style']],#}
{#                    ['font', ['bold', 'underline', 'clear']],#}
{#                    ['color', ['color']],#}
{#                    ['para', ['ul', 'ol', 'paragraph']],#}
{#                    ['table', ['table']],#}
{#                    ['insert', ['link', 'picture', 'video']],#}
{#                    ['view', ['fullscreen', 'help']]#}
{#                ]#}
{#            });#}
{#            $('p').css('margin-bottom', '0')#}
{#            $('.note-resizebar').css('display', 'none');#}
{#        });#}
{#    </script>#}
{#{% endblock %}#}
{##}
{#{% block contents %}#}
{#    {% load static %}#}
{#    <div class="container">#}
{#        <div class="row mt-5">#}
{#            <div class="col-12">#}
{#                <h4 style="font-weight: bold;">Q&A 게시판</h4>#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="row-mt-5">#}
{#            <!--본문-->#}
{#            <form action="" method="POST" enctype="multipart/form-data">#}
{#                {% csrf_token %}#}
{#                <div class="card" style="width: 100%;">#}
{#                    <!--제목,분류,작성일-->#}
{#                    <div class="card-header" style="padding: 0rem 0.2rem">#}
{#                        <div class="md-form form-group" style="margin-top: 8.5px;">#}
{#                            <div style="padding: 0 5.5px;">#}
{#                                <!-- <label for="{{ form.title.id_for_label }}"#}
{#                  class="col-sm-2 control-label">{{ form.title.label }}</label> -->#}
{#                                {{ form.category }}#}
{#                                {{ form.title }}#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <!--내용-->#}
{#                    {{ form.content }}#}
{#                </div>#}
{#        </div>#}
{##}
{#        <div class="card-footer" style="padding-left: 0px; margin-top:18px;">#}
{#            <div class="form-group">#}
{#                <div class="col-sm-12">#}
{#                    {{ form.upload_files }}#}
{#                    <small id="help" class="form-text text-muted" style="margin-bottom: -15px;">#}
{#                        &nbsp;&nbsp;[파일 업로드]&nbsp;&nbsp;<i class="fas fa-upload"></i>&nbsp;10MB 이하의 파일만 첨부 가능합니다. 여러 파일은#}
{#                        압축해서 업로드해주세요.#}
{#                    </small>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <div class="text-right" style="margin-top: 10px;">#}
{#            {% if edit %}#}
{#                <button type="submit" id="write" class="btn btn-sm">{{ edit }}</button>#}
{#            {% else %}#}
{#                <button type="submit" id="write" class="btn btn-sm">작성하기</button>#}
{#            {% endif %}#}
{#            <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">#}
{#        </div>#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}
{##}
{#{% block script %}#}
{#<script type="text/javascript">#}
{#    var checkUnload = true;#}
{#    $(window).on('beforeunload', function () {#}
{#        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";#}
{#    });#}
{#    $("#write").on("click", function () {#}
{#        checkUnload = false;#}
{#        $("submit").submit();#}
{#    });#}
{#</script>#}
{#{% endblock %}#}
{##}
{#{% if filename %}#}
{#    <script type="text/javascript">#}
{#        $('[href="{{ file_url }}"]').html("{{ filename }}");#}
{#        $('#upload_files-clear_id').css({opacity: '100', position: 'relative', 'pointer-events': 'auto'})#}
{##}
{#        $("#id_upload_files").change(function () {#}
{#            if ($('#id_upload_files').get(0).files.length == 1) {#}
{#                $(".col-sm-12").contents().get(0).nodeValue = '[첨부파일 변경 시 기존 파일은 삭제됩니다.]'#}
{#                $('#upload_files-clear_id').attr("checked", false)#}
{#                $('#upload_files-clear_id').prev().hide()#}
{#                $('#upload_files-clear_id').next().hide()#}
{#                $('#upload_files-clear_id').hide()#}
{#            }#}
{#        });#}
{##}
{#        $('#upload_files-clear_id').on('click', function () {#}
{#            if ($(this).prop('checked')) {#}
{#                $('#id_upload_files').hide()#}
{#                document.getElementById('id_upload_files').previousSibling.nodeValue = '[업로드 된 첨부파일을 삭제합니다.]'#}
{#            } else {#}
{#                $('#id_upload_files').show()#}
{#                document.getElementById('id_upload_files').previousSibling.nodeValue = '변경: '#}
{#            }#}
{#        });#}
{##}
{#        $('#write').click(function () {#}
{#            if ($('#id_upload_files').get(0).files.length == 1) {#}
{#                $('#fileChangeCheck').attr("checked", true)#}
{#            }#}
{#        });#}
{#    </script>#}
{#{% endif %}#}

boardapp/templates/boardapp/board_delete.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>글 삭제</h4>
            <h4>{{ target_board.title }}</h4>
        </div>
        <form action="{% url 'boardapp:delete' pk=target_board.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-4 mt-3">
        </form>

    </div>

{% endblock %}

boardapp/templates/boardapp/board_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="row-mt-5">
            <div class="col-12">
                <div class="card" style="width: 100%; background-color: ghostwhite">
                    <div style="text-align: center">
                        <div class="card-header">
                            <strong style="font-size: 2rem; float:left;">{{ target_board.title }}</strong>
                            <span style="float:right;">{{ target_board.created_at|date:'Y.m.d. H:i' }}</span>

                            <span style="display: none">{{ target_board.update_counter }}</span>
                            <!--작성자, 조회수-->
                            <div><br><br><br>
                                <div style="float:left;">작성자 : {{ target_board.writer.name }}</div>

                                <span style="float:right;">조회수 : {{ target_board.hits }}</span>
                            </div>
                            <br>
                        </div>
                        <!--내용-->
                        <div class="card-body" style="min-height: 400px; color:black;">
                            <div class="text-center" style="height: min-content">
                                <div>
                                    {% if target_board.image %}
                                        <img style="width:40%; border-radius: 2rem; margin: 2rem 0;"
                                             src="{{ target_board.image.url }}" alt="">
                                    {% endif %}
                                </div>
                                <div style="text-align: left;">
                                    {{ target_board.content | safe }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>

                    <form>
                        {% if target_board.writer == user %}
                            <a href="{% url 'boardapp:delete' pk=target_board.pk %}"
                               class="btn btn-danger rounded-pill col-1 row-1" style="float: right; margin: 16px;">
                                Delete
                            </a>
                            <a href="{% url 'boardapp:update' pk=target_board.pk %}"
                               class="btn btn-primary rounded-pill col-1 row-1" style="float: right; margin: 16px;">
                                Update
                            </a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div style="margin: 1rem">
        {% for comment in target_board.comment.all %}
            {% include 'commentapp/comment_detail.html' with comment=comment %}
        {% endfor %}


        {% include 'commentapp/comment_create.html' with board=target_board %}
    </div>


{% endblock %}


{#{% extends "base.html" %}#}
{#{% load bootstrap4 %}#}
{##}
{#{% block mobileView %}#}
{#    <meta name="viewport" content="width=800, user-scalable=yes">#}
{#{% endblock %}#}
{##}
{#{% block contents %}#}
{#    <br><br><br>#}
{#    <div class="container">#}
{#        <div class="row-mt-5">#}
{#            <div class="col-12">#}
{#                <!--본문-->#}
{#                <div class="card" style="width: 100%;">#}
{#                    <!--제목,분류,작성일-->#}
{#                    <div class="card-header">#}
{#                        <strong style="font-size: 18px;">{{ target_board.title }}</strong>#}
{#                        <span style="float:right;">{{ target_board.created_at|date:'Y.m.d. H:i' }}</span>#}
{#                    </div>#}
{#                    <div class="card-body" style="min-height: 400px; color:black;">#}
{#                        <!--작성자, 조회수-->#}
{#                        <div>#}
{#                            <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ target_board.writer }}</span>#}
{#                            <span style="float:right;">조회수 : {{ target_board.hits }}</span>#}
{#                        </div>#}
{#                        <hr>#}
{#                        <!--내용-->#}
{#                        <div>#}
{#                            {{ target_board.content | safe }}#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <br>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{##}
{#                <br>#}
{#                <div class="text-right" style="margin-top:-15px;">#}
{#                    {% if board_auth or request.user.level == '0' %}#}
{#                        <button class="btn btn-sm" id="detail_btn"#}
{#                                onclick="location.href='/board/{{ board.id }}/edit/'">수정#}
{#                        </button>#}
{#                        <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#delete_modal">삭제#}
{#                        </button>#}
{#                        <button class="btn btn-sm" id="detail_btn" onclick="location.href='/board/'">목록으로</button>#}
{#                    {% elif request.user.level == '1' %}#}
{#                        <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#delete_modal">삭제#}
{#                        </button>#}
{#                        <button class="btn btn-sm" id="detail_btn" onclick="location.href='/board/'">목록으로</button>#}
{#                    {% else %}#}
{#                        <button class="btn btn-sm" id="detail_btn" onclick="location.href='/board/'">목록으로</button>#}
{#                    {% endif %}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{##}
{##}
{#{% endblock %}#}

boardapp/templates/boardapp/board_list.html
{% extends "base.html" %}
{% load bootstrap4 %}

{#{% block content %}#}
{#    <div class="row mt-5">#}
{#        <div class="col-12">#}
{#            <table class="table">#}
{#                <thead class="thead-dark">#}
{#                <tr>#}
{#                    <th scope="col">#</th>#}
{#                    <th scope="col">제목</th>#}
{#                    <th scope="col">아이디</th>#}
{#                    <th scope="col">작성일</th>#}
{#                </tr>#}
{#                </thead>#}
{##}
{#                <tbody>#}
{#                {% for board in board_list %}#}
{#                    <tr>#}
{#                        <td><a href="{% url "boardapp:detail" pk=board.pk %}">{{ board.id }}</a></td>#}
{#                        <td><a href="{% url "boardapp:detail" pk=board.pk %}">{{ board.title }}</a></td>#}
{#                        <td>{{ board.writer.profile.nickname }}</td>#}
{#                        <td>{{ board.created_at }}</td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
{#    </div>#}
{#    <div style="text-align: center">#}
{#        <a href="{% url 'boardapp:create' %}" class="btn btn-primary rounded-pill col-3 mt-3 mb-3 px-2">#}
{#            글쓰기#}
{#        </a>#}
{#    </div>#}
{#{% endblock %}#}

{% block content %}

    <div class="container">
        <div class="row mt-5">
            <div class="col-12">
                <h2 style="font-weight: bold; text-align: center">Q & A</h2>
            </div>
        </div>
        <br>
        <div>
            <table class="table table-sm table-hover">
                <thead class="thead-dark" style="border-top: 1px solid #dee2e6;">
                <tr class="text-center">
                    <th style="font-weight: bold; font-size: 16px;">제목</th>
                    <th style="font-weight: bold; font-size: 16px;">작성자</th>
                    <th style="font-weight: bold; font-size: 16px;">등록일</th>
                    <th style="font-weight: bold; font-size: 16px;">조회수</th>
                </tr>
                </thead>

                <tbody>
                {% for board in board_list %}
                    <tr class="text-center" style="cursor: pointer;"
                        onclick="location.href='{% url "boardapp:detail" pk=board.pk %}'">
                        <td style="width: 50%; font-weight: 600;" class="text-center">{{ board.title }}</td>
                        <td style="font-weight: 500;">{{ board.writer.name }}</td>
                        <td style="font-weight: 500;">{{ board.created_at | date:'Y. m. d' }}</td>
                        <td style="font-weight: 500;">{{ board.hits }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div style="margin-top: 30px;">
            <form action="" method="GET">
                <div class="col">
                    <div style="float: right;" class="form-row">
                        <div class="form-row">
                            <div class="col" style="margin-top: 10px;">
                                <select name="type" style="width: 6em;" class="custom-select custom-select-sm">
                                    <option value="all">전체</option>
                                    <option value="title_content">제목+내용</option>
                                    <option value="title">제목</option>
                                    <option value="content">내용</option>
                                </select>
                            </div>
                            <div class="col" style="margin-top: 10px;">
                                <input type="text" name="q" value="" class="form-control form-control-sm"
                                       style="width: 15em;" placeholder="검색어를 입력해주세요">
                            </div>
                            <div class="col" style="margin-top: 10px;">
                                <button class="btn btn-sm btn-secondary" type="submit" id="search_btn">검색</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div>
                <div style="margin-top: 30px;">
                    <a href="{% url 'boardapp:create' %}" style="color: white; background-color: #1f75d9;
                    padding:8px 15px 8px 15px; border-radius: 2rem; margin: 3rem;">
                        글쓰기</a>

                </div>
            </div>
        </div>
        <br><br><br>


    </div>
    <div style="display: flex; justify-content: center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                           tabindex="-1">이전</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">이전</a>
                    </li>
                {% endif %}

                {% for page in page_range %}
                    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                        <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}">{{ page }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}">다음</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">다음</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>


{% endblock %}

boardapp/templates/boardapp/board_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>글 수정</h4>
        </div>
        <form action="{% url 'boardapp:update' pk=target_board.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3">
        </form>
    </div>


    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}