accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views
from accountapp.views import MypageView

app_name = 'accountapp'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('mypage/<int:pk>', MypageView.as_view(), name='mypage'),
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('trainer_register/', views.TrainerRegisterView.as_view(), name='trainer_register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('update/', views.password_update_view, name='password_update'),
    path('delete/', views.account_delete_view, name='account_delete'),
]

boardapp/urls.py
from django.urls import path

from boardapp.views import BoardListView, BoardCreateView, BoardDetailView, BoardUpdateView, BoardDeleteView

app_name = 'boardapp'

urlpatterns = [
    path('list/', BoardListView.as_view(), name='list'),
    path('create/', BoardCreateView.as_view(), name='create'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),
]

chatapp/urls.py
from django.urls import path

from chatapp.views import main_view

app_name = 'chatapp'

urlpatterns = [
    path('', main_view, name='main_view'),
]

health_partner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from health_partner.views import HomeView

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),

                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('boards/', include('boardapp.urls')),
                  path('trainers/', include('trainerapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('videos/', include('videoapp.urls')),
                  path('trainercomments/', include('trainercommentapp.urls')),
                  path('chats/', include('chatapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'


urlpatterns =[
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
]

accountapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.hashers import check_password

from accountapp.choice import *
from .models import User


def hp_validator(value):
    if len(str(value)) != 10:
        raise forms.ValidationError('정확한 핸드폰 번호를 입력해주세요.')


# 로그인 폼
class LoginForm(forms.Form):
    user_id = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', }),
        error_messages={
            'required': '아이디을 입력해주세요.'
        },
        max_length=32,
        label='아이디'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', }),
        error_messages={
            'required': '비밀번호를 입력해주세요.'
        },
        label='비밀번호'
    )

    def clean(self):
        cleaned_data = super().clean()
        user_id = cleaned_data.get('user_id')
        password = cleaned_data.get('password')

        if user_id and password:
            try:
                user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                self.add_error('user_id', '아이디가 존재하지 않습니다.')
                return

            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다.')


# 일반회원정보 수정 폼
class CustomUserChangeForm(UserChangeForm):
    password = None
    hp = forms.IntegerField(label='연락처', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength': '11', 'oninput': "maxLengthCheck(this)", }),
                            )
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength': '8', }),
                           )
    is_trainer = forms.ChoiceField(choices=IS_TRAINER_CHOICES, label='트레이너/일반인', widget=forms.Select(
        attrs={'class': 'form-control', }),
                                   )

    class Meta:
        model = get_user_model()
        fields = ['hp', 'name', 'is_trainer']


# 트레이너 회원정보 수정 폼
class CustomTrainerChangeForm(UserChangeForm):
    password = None
    hp = forms.IntegerField(label='연락처', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength': '11', 'oninput': "maxLengthCheck(this)", }),
                            )
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength': '8', }),
                           )
    is_trainer = forms.ChoiceField(choices=IS_TRAINER_CHOICES, label='트레이너/일반인', widget=forms.Select(
        attrs={'class': 'form-control', }),
                                   )
    trainer_num = forms.ChoiceField(label='자격증번호', widget=forms.Select(
        attrs={'class': 'form-control', }),
                                    )

    class Meta:
        model = get_user_model()
        fields = ['hp', 'name', 'is_trainer', 'trainer_num']


# 회원탈퇴 비밀번호확인 폼
class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control', }),
                               )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password

        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')



# 비밀번호 변경 폼
class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
            'style': 'margin-top:-15px;'
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })


# 트레이너 회원가입 폼
class TrainerRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(TrainerRegisterForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            # 'class': 'form-control col-sm-10',
            'class': 'form-control',
            # 'placeholder': '아이디를 입력해주세요.',
            'autofocus': False
        })
        self.fields['password1'].label = '비밀번호'
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 입력해주세요.',
        })
        self.fields['password2'].label = '비밀번호 확인'
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 다시 입력해주세요.',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '회원가입 후 입력하신 메일로 본인인증 메일이 전송됩니다.',
        })
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "아이디, 비밀번호 찾기에 이용됩니다.",
        })
        self.fields['hp'].label = '핸드폰번호'
        self.fields['hp'].validators = [hp_validator]
        self.fields['hp'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "'-'를 제외한 숫자로 입력해주세요",
        })
        self.fields['trainer_num'].label = '자격증번호'
        self.fields['trainer_num'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "트레이너 자격증 번호를 입력해주세요",
        })

    class Meta:
        model = User
        fields = ['user_id', 'password1', 'password2', 'email', 'name', 'hp', 'trainer_num']

    def save(self, commit=True):
        user = super(TrainerRegisterForm, self).save(commit=False)
        user.level = '2'
        user.is_trainer = '트레이너'
        user.save()

        return user


# 일반인 회원가입 폼
class RegisterForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            # 'class': 'form-control col-sm-10',
            'class': 'form-control',
            'autofocus': False,
            # 'placeholder': '아이디를 입력해주세요.',
        })
        self.fields['password1'].label = '비밀번호'
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 입력해주세요.',
        })
        self.fields['password2'].label = '비밀번호 확인'
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 다시 입력해주세요.',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['hp'].label = '핸드폰번호'
        self.fields['hp'].validators = [hp_validator]
        self.fields['hp'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "'-'를 제외한 숫자로 입력해주세요",
        })

    class Meta:
        model = User
        fields = ['user_id', 'password1', 'password2', 'email', 'name', 'hp']

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.level = '3'
        user.is_trainer = '일반인'
        user.save()

        return user

accountapp/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, FormView, DetailView

from accountapp.decorators import logout_message_required, login_message_required
from accountapp.forms import TrainerRegisterForm, LoginForm, RegisterForm, CustomPasswordChangeForm, CheckPasswordForm
from accountapp.models import User
from trainerapp.models import Trainer


@method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'accountapp/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=user_id, password=password)

        if user is not None:
            self.request.session['user_id'] = user_id
            login(self.request, user)

        return super().form_valid(form)


def logout_view(request):
    logout(request)
    return redirect('/')


@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'accountapp/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True

            if request.POST.get('trainer_register') == 'trainer_register':
                return redirect('/accounts/trainer_register/')
            else:
                return redirect('/accounts/register/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'accountapp/agreement.html')


class TrainerRegisterView(CreateView):
    model = User
    template_name = 'accountapp/trainer_register.html'
    form_class = TrainerRegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False

        url = settings.LOGIN_REDIRECT_URL
        if request.user.is_authenticated:
            return HttpResponseRedirect(url)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, "회원가입 성공.")
        return reverse_lazy('home')

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_success_url())


class RegisterView(CreateView):
    model = User
    template_name = 'accountapp/register.html'
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False

        url = settings.LOGIN_REDIRECT_URL
        if request.user.is_authenticated:
            return HttpResponseRedirect(url)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, "회원가입 성공.")
        return reverse_lazy('home')

    def form_valid(self, form):
        self.objects = form.save()
        return redirect(self.get_success_url())


@login_message_required
def password_update_view(request):
    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            # logout(request)
            messages.success(request, "비밀번호를 성공적으로 변경하였습니다.")
            return redirect('/')
    else:
        password_change_form = CustomPasswordChangeForm(request.user)

    return render(request, 'accountapp/password_update.html', {'password_change_form': password_change_form})


@login_message_required
def account_delete_view(request):
    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)

        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "회원탈퇴가 완료되었습니다.")
            return redirect('/accounts/login/')
    else:
        password_form = CheckPasswordForm(request.user)

    return render(request, 'accountapp/account_delete.html', {'password_form': password_form})


class MypageView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/mypage.html'

    def get_context_data(self, **kwargs):
       object_list = Trainer.objects.filter(trainer=self.get_object())
       return super().get_context_data(object_list=object_list, **kwargs)


accountapp/templates/accountapp/login.html
{% extends "accountapp/user_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=480, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row justify-content-md-center">
        <div style="position: absolute; top: 40%; height: 476.06px; margin-top: -238.03px;">
            <div class="card" style="width: 30rem; border-radius: 3rem;">
                <div class="card-body">
                    <div class="text-center">
                        <img src="{% static 'img/logo2.jpg' %}" style="width:60%; margin:30px;">
                    </div>

                    <form method="POST" action="." novalidate>
                        {% csrf_token %}

                        <div class="mb-4 md-form">
                            <label name="label_user_id" for="{{ form.user_id.id_for_label }}"><i class="fas fa-user"></i>&nbsp;&nbsp;{{ form.user_id.label }}</label>
                            {{ form.user_id }}
                            <script type="text/javascript">
                                if (document.getElementsByName('user_id')[0].value != '') {
                                    document.getElementsByName('label_user_id')[0].setAttribute('class', 'active');
                                }
                            </script>
                            {% if form.user_id.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('user_id')[0].setAttribute('class',
                                    'form-control is-invalid')
                            </script>
                            {% for error in form.user_id.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div class="mb-4 md-form">
                            <label for="{{ form.password.id_for_label }}"><i class="fas fa-lock"></i>&nbsp;&nbsp;{{ form.password.label }}</label>
                            {{ form.password }}

                            {% if form.password.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
                            </script>
                            {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <!-- {{ login_form }} -->
                        <label>
                            <input type="checkbox" name="remember_session"/>
                            <span style="padding-bottom: 35px;">로그인 상태 유지</span>
                        </label>
                        <br>
                        <!-- <input type="checkbox" name="remember_session" > 로그인 상태 유지<br><br> -->

                        <button type="submit" style="opacity: 90%; font-size: 16px; margin-top: -5px; border-radius: 3rem" class="btn btn-blue btn-lg btn-block ">로그인</button>
                    </form>
                    <div style="text-align: center;">
                        <a style="color:gray; font-size: 14px;" href="{% url 'accountapp:agreement' %}">회원가입</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/mypage.html
{% extends 'base.html' %}

{{% block content %}

    <div>
        <section class="pt-4">
            <div class="container px-lg-5">
                <!-- Page Features-->
                <div class="row gx-lg-5">
                    <div class="col-6 mb-5">
                        {% if target_user.profile %}
                            <div class="card bg-light border-0 h-100">
                                <div class="card-body text-center ">
                                    <img src="{{ target_user.profile.image.url }}" alt=""
                                         style="height: 10rem; width: 10rem; box-shadow : 2px 2px 5px #ccc; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
                                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i
                                            class="bi bi-collection"></i>
                                    </div>
                                    <h2>
                                        {{ target_user.profile.nickname }}
                                        {% if target_user == user %}
                                            <a class="material-icons"
                                               style="box-shadow: 2px 2px 5px #ccc; border-radius: 10rem; padding: .5rem"
                                               href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                                                edit
                                            </a>
                                        {% endif %}
                                    </h2>
                                    <h5 style="margin-bottom: 3rem">
                                        {{ target_user.profile.message }}
                                    </h5>
                                    <p class="mb-0"></p>
                                </div>
                            </div>
                        {% else %}
                            {% if target_user == user %}
                                <div class="card bg-light border-0 h-100">
                                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                            <span class="material-icons" style="font-size:100px">
                                account_circle
                                </span>
                                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4">
                                            <i
                                                    class="bi bi-collection"></i></div>
                                        <h2 class="fs-4 fw-bold">프로필을 설정하세요.
                                            <a class="material-icons"
                                               style="box-shadow: 2px 2px 5px #ccc; border-radius: 10rem; padding: .5rem"
                                               href="{% url 'profileapp:create' %}">
                                                create
                                            </a>
                                        </h2>
                                        <p class="mb-0"></p>
                                    </div>
                                </div>

                            {% else %}
                                <h3>
                                    로그인이 필요합니다.
                                </h3>
                            {% endif %}
                        {% endif %}
                    </div>

                    <div class="col-6 mb-5">
                        <a href="">
                            <div class="card bg-light border-0 h-100">
                                <div class="card-body text-center">
                            <span class="material-icons" style="font-size:100px">
                                account_circle
                                </span>
                                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i
                                            class="bi bi-collection"></i></div>
                                    <h2 class="fs-4 fw-bold">등록한 트레이너</h2>
                                </div>
                            </div>
                        </a>
                    </div>

                    <div class="row">

                        <div class="col-lg-4 mb-5">
                            <a href="{% url 'chatapp:main_view' %}">
                                <div class="card bg-light border-0 h-100">
                                    <div class="card-body text-center">
                                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-4"><i
                                                class="bi bi-collection"></i></div>
                                        <h2 class="fs-4 fw-bold" style="font-size: 1.5rem">라이브 PT</h2>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-lg-4 mb-5">
                            <a href="{% url 'boardapp:list' %}">
                                <div class="card bg-light border-0 h-100">
                                    <div class="card-body text-center ">
                                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-4"><i
                                                class="bi bi-cloud-download"></i></div>
                                        <h2 class="fs-4 fw-bold" style="font-size: 1.5rem">나의 질문 내역</h2>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-lg-4 mb-5">
                            {% if target_user == user %}

                                <div class="card bg-light border-0 h-100">
                                <div class="card-body text-center">
                                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-4"><i
                                            class="bi bi-card-heading"></i></div>
                                    <h2 class="fs-4 fw-bold" style="font-size: 1.5rem">개인정보 수정</h2>
                                    <div class="col-lg-1.5 mb-5" style="">
                                        <a class="material-icons"
                                           style="box-shadow: 2px 2px 5px #ccc; border-radius: 10rem; padding: .5rem"
                                           href="{% url 'accountapp:password_update' %}">
                                            manage_accounts
                                        </a>
                                        <a class="material-icons"
                                           style="box-shadow: 2px 2px 3px red; border-radius: 10rem; padding: .5rem"
                                           href="{% url 'accountapp:account_delete' %}">
                                            person_remove
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-12 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center ">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i
                                        class="bi bi-code"></i></div>
                                <h2 class="fs-4 fw-bold">오늘의 식단</h2>
                                <p class="mb-0">아침 : 달걀, 현미밥, 버섯볶음 <br> 점심 : 돼지고기볶음, 콩밥, 오이무침 <br> 저녁 : 닭가슴살, 달걀</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i
                                        class="bi bi-patch-check"></i></div>
                                <h2 class="fs-4 fw-bold">추천 영상</h2>
                                <p class="mb-0"> 아직 미구현 </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

accountapp/templates/accountapp/user_base.html
<html>

<head>
    <title>HP</title>
    <meta charset='utf-8'>
    {% block mobileView %}
    {% endblock %}


    {% load static %}
    <link rel="shortcut icon" href="{% static 'img/reborn_favicon.ico' %}">
    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <!-- CheckBoxCSS -->
    <link rel="stylesheet" href="{% static 'css/users/checkbox.css' %}" type="text/css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.11.0/css/mdb.min.css" rel="stylesheet">

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
    </script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.11.0/js/mdb.min.js">
    </script>

    {% block header %}
    {% endblock %}
</head>

<body style="background-color: #d6d6d6;">

{% block contents %}
{% endblock %}


{% if messages %}
    {% for message in messages %}
        {% if message.tags %}
            <script>
                alert("{{ message.message }}")
            </script>
        {% endif %}
    {% endfor %}
{% endif %}
</body>

</html>