accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views
from accountapp.views import MypageView

app_name = 'accountapp'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('mypage/<int:pk>', MypageView.as_view(), name='mypage'),
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('trainer_register/', views.TrainerRegisterView.as_view(), name='trainer_register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('update/', views.password_update_view, name='password_update'),
    path('delete/', views.account_delete_view, name='account_delete'),
]

boardapp/urls.py
from django.urls import path

from boardapp.views import BoardListView, BoardCreateView, BoardDetailView, BoardUpdateView, BoardDeleteView

app_name = 'boardapp'

urlpatterns = [
    path('list/', BoardListView.as_view(), name='list'),
    path('create/', BoardCreateView.as_view(), name='create'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),
]

chatapp/urls.py
from django.urls import path

from chatapp.views import main_view

app_name = 'chatapp'

urlpatterns = [
    path('', main_view, name='main_view'),
]

health_partner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from health_partner.views import HomeView

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),

                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('boards/', include('boardapp.urls')),
                  path('trainers/', include('trainerapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('videos/', include('videoapp.urls')),
                  path('trainercomments/', include('trainercommentapp.urls')),
                  path('chats/', include('chatapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainerapp/urls.py
from django.urls import path

from trainerapp import views
from trainerapp.views import TrainerListView, TrainerCreateView, TrainerDetailView, TrainerUpdateView, \
    TrainerDeleteView, InquiredBoardView

app_name = "trainerapp"

urlpatterns = [
    path('list/', TrainerListView.as_view(), name='list'),
    path('create/', TrainerCreateView.as_view(), name='create'),
    path('detail/<int:pk>', TrainerDetailView.as_view(), name='detail'),
    path('update/<int:pk>', TrainerUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TrainerDeleteView.as_view(), name='delete'),
    path('board/<int:pk>', InquiredBoardView.as_view(), name='board'),
]

videoapp/urls.py
from django.urls import path

from videoapp.views import VideoListView, VideoDetailView, add_youtube

app_name = "videoapp"

urlpatterns = [
    path('list/', VideoListView.as_view(), name='list'),
    path('detail/<int:pk>', VideoDetailView.as_view(), name='detail'),
    path('youtube/', add_youtube, name='csv업데이트')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'Jua', sans-serif; background-color: aliceblue">
{% include 'header.html' %}

<hr>


{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5 my-3">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
{% endblock %}

<hr>
{% include 'footer.html' %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"
></script>
<script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"
></script>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"
></script>

<!-- MDB -->
<script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
<script type="module">
        import "/static/js/containerEffect.mjs";
</script>
{% block custom_script %} {% endblock %}
</body>
</html>

templates/footer.html
<footer class="footer bg-black" style="font-family: 'Jua', sans-serif;">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 h-100 text-md-left text-lg-start my-auto">
                ABOUT
                <br>
                2021-2학기 졸업프로젝트 작품
                <br>
                팀명 : 코딩하는 헬린이
                <br>
                사용한 기술스택 : Django, Javascript, CSS, Nginx, Gunicorn,
                <br>
                AWS, Docker, Bootstrap ...
            </div>
            <div class="col-lg-6 col-md-6 h-100 text-center text-lg-end my-auto">
                MEMBERS
                <br>
                팀장 : 심예원
                <br>
                팀원 : 문지환
                <br>
                팀원 : 오예지
                <br>
                팀원 : 신윤철
            </div>
        </div>
    </div>
</footer>


templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HP</title>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />

    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />

    <!-- AnimateCSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />  

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">

    {#  GOOGLE MATERIAL ICONS  #}
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {# DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {% block extrahead %} {% endblock %}

</head>

templates/header.html
<div style="font-family: 'Jua', sans-serif; margin-top:2rem; background-color: aliceblue">
    <div style="text-align: center; margin: 1rem 0;">
        <div>
            <a href="{% url 'home' %}" style="text-decoration: none; color: black">
                <h1 class="HP_font">Health Partner</h1>
            </a>
        </div>
    </div>
    <div style="margin: 2rem; text-align: center">
            <a href="{% url 'boardapp:list' %}" style="margin: 0.7rem"><span>Q&A</span></a>
            <a href="{% url 'trainerapp:list' %}" style="margin: 0.7rem"><span>트레이너</span></a>
            <a href="{% url 'videoapp:list' %}" style="margin: 0.15rem"><span>헬스정보</span></a>
            {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}" style="margin: 0.7rem">
{#                       request.path는 요청받은 경로를 의미하며 쉽게 말하면 login후 해당 url을 누른 페이지로 돌아간다는 말이다.#}
                    <span>로그인</span>
                </a>
                <a href="{% url 'accountapp:agreement' %}" style="margin: 0.7rem">
                    <span>회원가입</span>
                </a>
            {% else %}
                <a href="{% url 'accountapp:mypage' pk=user.pk %}" style="margin: 0.7rem">
                    <span>마이페이지</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" style="margin: 0.7rem">
                    <span>로그아웃</span>
                </a>
            {% endif %}
    </div>

</div>

{##}
{#<div style="font-family: 'Jua', sans-serif; margin-top:1.5rem">#}
{#    <nav class="navbar navbar-white static-top" style="background-color: aliceblue">#}
{#        <div class="container">#}
{#            <div class="navbar-brand" style="font-size: 1rem">#}
{#                <a href="{% url 'boardapp:list' %}" style="margin: 0.15rem"><span>Q&A</span></a>#}
{#                <a href="{% url 'videoapp:list' %}" style="margin: 0.15rem"><span>트레이너</span></a>#}
{#                <a href="#" style="margin: 0.15rem"><span>헬스정보</span></a>#}
{#            </div>#}
{#            <div class="navbar-brand" style="font-size: 1rem">#}
{#                {% if not user.is_authenticated %}#}
{#                    <a href="{% url 'accountapp:login' %}?next={{ request.path }}" style="margin: 0.15rem">#}
{#                           request.path는 요청받은 경로를 의미하며 쉽게 말하면 login후 해당 url을 누른 페이지로 돌아간다는 말이다.#}
{#                        <span>로그인</span>#}
{#                    </a>#}
{#                    <a href="{% url 'accountapp:agreement' %}" style="margin: 0.15rem">#}
{#                        <span>회원가입</span>#}
{#                    </a>#}
{#                {% else %}#}
{#                    <a href="{% url 'accountapp:mypage' pk=user.pk %}" style="margin: 0.15rem">#}
{#                        <span>마이페이지</span>#}
{#                    </a>#}
{#                    <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" style="margin: 0.15rem">#}
{#                        <span>로그아웃</span>#}
{#                    </a>#}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
{#    </nav>#}
{#</div>#}
{##}
{#<div style="font-family: 'Jua', sans-serif; text-align: center; margin: 1rem 0;">#}
{#    <div>#}
{#        <a href="{% url 'home' %}" style="text-decoration: none; color: black">#}
{#            <h1 class="HP_font">Health Partner</h1>#}
{#        </a>#}
{#    </div>#}
{#</div>#}

templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="my-5"></div>

        <!-- heading -->
    <div class="container" style="text-align: center">
      <h2><strong>전문 트레이너</strong>와 함께 <strong>홈트레이닝</strong> 해보세요!</h2>
    </div>
    <div class="my-4"></div>

    <!-- Cards -->
        <!-- cards -->
    <div class="container" style="max-width: 890px; text-align: center">
      <div class="row row-cols-1 row-cols-md-3 g-4">

        <div class="col">
          <div class="card h-100">
            <div
              class="bg-image hover-overlay ripple"
              data-mdb-ripple-color="light"
            >
              <img
                src="media/trainer/김종국.jpg"
                class="card-img-top"
                alt="..."
              />
              <a href="{% url 'trainerapp:list' %}">
                <div
                  class="mask"
                  style="background-color: rgba(251, 251, 251, 0.15)"
                ></div>
              </a>
              <div class="card-body">
                <p class="card-text">
                  클릭시 뛰어난 트레이너들을 <br>만나 볼 수 있습니다!
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card h-100">
            <div
              class="bg-image hover-overlay ripple"
              data-mdb-ripple-color="light"
            >
              <img
                src="media/trainer/김계란.jpg"
                class="card-img-top"
                alt="..."
              />
              <a href="{% url 'trainerapp:list' %}">
                <div
                  class="mask"
                  style="background-color: rgba(251, 251, 251, 0.15)"
                ></div>
              </a>
              <div class="card-body">
                <p class="card-text">
                  클릭시 뛰어난 트레이너들을 <br>만나 볼 수 있습니다!
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card h-100">
            <div
              class="bg-image hover-overlay ripple"
              data-mdb-ripple-color="light"
            >
              <img
                src="media/trainer/조준.jpg"
                class="card-img-top"
                alt="..."
              />
              <a href="{% url 'trainerapp:list' %}">
                <div
                  class="mask"
                  style="background-color: rgba(251, 251, 251, 0.15)"
                ></div>
              </a>
              <div class="card-body">
                <p class="card-text">
                  클릭시 뛰어난 트레이너들을 <br>만나 볼 수 있습니다!
                </p>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <hr class="my-5">
    </div>

    <!-- heading -->
    <div class="container" style="text-align: center">
      <h2><strong>헬스</strong> 관련 <strong>최신 트렌드</strong>를 확인하세요!</h2>
    </div>
    <div class="my-4"></div>

    <!-- Cards -->
    <div class="container" style="text-align: center">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">
                  <!-- content here -->
                  <img src="static/img/word_cloud1.png" alt="" class="src">
                    <div class="card-body">
                        <h5 class="card-title">Word Cloud</h5>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card">
                  <img src="static/img/word_cloud2.png" alt="" class="src">
                    <div class="card-body">
                        <h5 class="card-title">분석 그래프</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
      <hr class="my-5">
    </div>

    <!-- heading -->
    <div class="container" style="text-align: center">
      <h2><strong>추천 영상</strong></h2>
    </div>
    <div class="my-4"></div>

    <!-- Cards -->
    <div class="container" style="text-align: center">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">
                    <iframe height="300" src="https://www.youtube.com/embed/iOSYLKBk894" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="card-body">
                        <h5 class="card-title">저희 사이트의 추천 영상을 확인하세요 !</h5>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card">
                    <iframe height="300" src="https://www.youtube.com/embed/7NPwSCjqka0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="card-body">
                        <h5 class="card-title">저희 사이트의 추천 영상을 확인하세요 !</h5>
                    </div>
                </div>
            </div>

        </div>
    </div>



    <div class="my-5"></div>
    <div class="container">
      <hr class="my-2" />
    </div>
{% endblock %}