accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views
from accountapp.views import MypageView

app_name = 'accountapp'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('mypage/<int:pk>', MypageView.as_view(), name='mypage'),
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('trainer_register/', views.TrainerRegisterView.as_view(), name='trainer_register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('update/', views.password_update_view, name='password_update'),
    path('delete/', views.account_delete_view, name='account_delete'),
]

chatapp/urls.py
from django.urls import path

from chatapp.views import main_view

app_name = 'chatapp'

urlpatterns = [
    path('', main_view, name='main_view'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

health_partner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from health_partner.views import HomeView

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),

                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('boards/', include('boardapp.urls')),
                  path('trainers/', include('trainerapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('videos/', include('videoapp.urls')),
                  path('trainercomments/', include('trainercommentapp.urls')),
                  path('chats/', include('chatapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainercommentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView
from trainercommentapp.views import TrainerCommentCreateView, TrainerCommentDeleteView

app_name = 'trainercommentapp'

urlpatterns = [
    path('create/', TrainerCommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', TrainerCommentDeleteView.as_view(), name='delete'),
]

trainercommentapp/models.py
from django.db import models

# Create your models here.
from accountapp.models import User
from trainerapp.models import Trainer


class TrainerComment(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True, related_name='trainer_comment')
    member = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='trainer_comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now=True)


trainercommentapp/forms.py
from django.forms import ModelForm

from trainercommentapp.models import TrainerComment


class TrainerCommentCreationForm(ModelForm):
    class Meta:
        model = TrainerComment
        fields = ['content']

trainercommentapp/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView

from trainerapp.models import Trainer
from trainercommentapp.decorators import comment_ownership_required
from trainercommentapp.forms import TrainerCommentCreationForm
from trainercommentapp.models import TrainerComment


class TrainerCommentCreateView(CreateView):
    model = TrainerComment
    form_class = TrainerCommentCreationForm
    template_name = 'trainercommentapp/comment_create.html'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.trainer = Trainer.objects.get(id=self.request.POST['trainer_pk'])
        temp_comment.member = self.request.user
        temp_comment.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('trainerapp:board', kwargs={'pk': self.object.trainer.pk})





@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class TrainerCommentDeleteView(DeleteView):
    model = TrainerComment
    context_object_name = 'target_comment'
    template_name = 'trainercommentapp/comment_delete.html'

    def get_success_url(self):
        return reverse('trainerapp:board', kwargs={'pk': self.object.trainer.pk})

trainercommentapp/templates/trainercommentapp/comment_create.html
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>댓글</h4>
        </div>
        <form action="{% url 'trainercommentapp:create' %}" method="post">
            {% csrf_token %}

            {% bootstrap_form form %}

            {% if user.is_authenticated %}
                <input type="submit" value="댓글달기" class="btn btn-dark rounded-pill col-4 mt-3">
            {% else %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}"
                   class="btn btn-dark rounded-pill col-4 mt-3">
                    Login
                </a>
            {% endif %}

            <input type="hidden" name="trainer_pk" value="{{ trainer.pk }}">
        </form>
    </div>

{% endblock %}

trainercommentapp/templates/trainercommentapp/comment_delete.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>댓글을 삭제합니다.</h4>
        </div>
        <form action="{% url 'trainercommentapp:delete' pk=target_comment.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="확인" class="btn btn-danger rounded-pill col-4 mt-3">
        </form>

    </div>

{% endblock %}

trainercommentapp/templates/trainercommentapp/comment_detail.html



<div style="border: 1px solid; text-align: left; padding: 4%; margin: 1rem 0;
border-radius: 1rem; border-color: #bbb">
    <div>
        <strong>
            {{ trainercomment.member.name }}
        </strong>
        &nbsp&nbsp&nbsp
        <span style="font-size: 12px">{{ trainercomment.created_at }}</span>
    </div>
    <div>
        {{ trainercomment.content }}
    </div>
    {% if trainercomment.writer == user %}
    <div style="text-align: right">
        <a href="{% url 'commentapp:delete' pk=trainercomment.pk %}"
           class="btn btn-danger btn-sm rounded-pill mt-2">
            댓글삭제
        </a>
    </div>
    {% endif %}
</div>